INSERT INTO post(postId, title, image, text, upvote, downvote, category, createdAt, updatedAt, UserUserId)
VALUES ( 1, 'First Post', NULL, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed egestas egestas fringilla phasellus. Cras sed felis eget velit. Tortor pretium viverra suspendisse potenti. Amet risus nullam eget felis eget. Integer feugiat scelerisque varius morbi enim. Velit euismod in pellentesque massa placerat duis. Amet purus gravida quis blandit turpis cursus in. Non nisi est sit amet. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Diam vulputate ut pharetra sit amet aliquam id. Risus viverra adipiscing at in tellus integer feugiat. Elit duis tristique sollicitudin nibh sit. Dictum at tempor commodo ullamcorper. Amet est placerat in egestas erat. Ridiculus mus mauris vitae ultricies. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Aenean pharetra magna ac placerat. Adipiscing bibendum est ultricies integer quis auctor. Neque viverra justo nec ultrices dui sapien eget mi.
				Faucibus a pellentesque sit amet porttitor eget dolor morbi. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Quis eleifend quam adipiscing vitae proin sagittis. Pretium vulputate sapien nec sagittis aliquam malesuada. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Turpis egestas sed tempus urna et pharetra pharetra. Facilisi nullam vehicula ipsum a arcu. Tempus urna et pharetra pharetra massa. Nulla porttitor massa id neque aliquam vestibulum morbi. Id porta nibh venenatis cras sed felis eget velit aliquet.
				Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Etiam sit amet nisl purus. Quam elementum pulvinar etiam non quam lacus suspendisse. Lacus viverra vitae congue eu consequat ac felis donec et. Semper viverra nam libero justo laoreet sit. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Velit aliquet sagittis id consectetur purus ut. Placerat orci nulla pellentesque dignissim enim sit. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Non consectetur a erat nam at lectus. Et tortor at risus viverra adipiscing at in tellus. Sit amet purus gravida quis blandit turpis cursus in hac.'
       , NULL, NULL, /* category: */ 2, DATE (), DATE (), /* UserUserId: */ 2)
        , ( 2, 'Jon Snow', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/3a1483fe-dc79-4448-8137-c21bf219a1d4/d8pa14z-bf4e5dc1-ac03-48c0-bd62-5ccab261f04b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzNhMTQ4M2ZlLWRjNzktNDQ0OC04MTM3LWMyMWJmMjE5YTFkNFwvZDhwYTE0ei1iZjRlNWRjMS1hYzAzLTQ4YzAtYmQ2Mi01Y2NhYjI2MWYwNGIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.9XvkdiCH08ai8aUFL_uOpzzQpN8dCBPUOk71JNlzkjQ', 'Jon was born in 283 AC, near the end of Roberts Rebellion, and he was named by Lord Eddard Stark. One tale says Jon was named after Lord Jon Arryn, Eddards second father. The identity of Jons mother is a mystery, and several suggestions have been made by those who know the Starks. Jon is unaware of his mothers identity and Eddard refuses to speak of her. When Eddard returned from the war, he brought the newborn Jon to Winterfell, insisting on raising him with the rest of his family. Jon and his wet nurse had been installed in the castle before the arrival of Eddards new wife, Catelyn Tully, and his young son and heir, Robb Stark, from Riverrun, which Catelyn did not take well.
				Lord Eddard was fiercely protective of Jon and refused to send him away. Jon was raised at Winterfell with his half-siblings, where he was tutored by Maester Luwin, and trained at arms by the master-at-arms, Ser Rodrik Cassel. Jon has trained at swordplay since he was old enough to walk, together with Robb, whom he came to view as his "best friend, rival and constant companion," and later also with Theon Greyjoy, after the latter came to Winterfell following the conclusion of Greyjoss Rebellion. Jon learned how to swim in the great moat at Winterfell; he is considered a strong swimmer.
				Jon grew close to his true-born siblings, especially Robb and Arya. Because they look alike, Arya came to believe that she was bastard-born as well, but Jon reassured his half-sister this was not the case. As a young child Jon and Robb built a great mountain of snow on top of a gate, hoping to push it on someone passing by. They were discovered by Mance Rayder, a ranger from the Nights Watch who had accompanied Lord Commander Qorgyle to Winterfell. The ranger promised not to tell anyone, and Jon and Robb succeeded in their ploy, being chased around the yard by Fat Tom, their victim. Jon and Robb would often play a game of sword-play, in which they would pretend to be great heroes (including Florian the Fool, Prince Aemon the Dragonknight, King Daeron I Targaryen, and Ser Ryam Redwyne). Once, when Jon called out that he was "Lord of Winterfell," Robb informed him that it was impossible due to his bastardy, which would become a sore memory for Jon. Another time, Jon covered himself in flour and hid in one of the empty tombs in the crypt of Winterfell, and jumped out to scare Sansa, Arya, and Bran, who had been brought to the crypts by Robb.
				Since he was young, Jons hero was King Daeron, the Young Dragon, who had conquered Dorne at the age of fourteen. Lord Eddard had dreamed about raising new lords and settling them in the abandoned holdfasts in the New Gift, and Jon believes that, had winter come and gone more quickly, he might have been chosen to hold one of the settlements in his fathers name.'
        , NULL, NULL, /* category: */ 3, DATE (), DATE (), /* UserUserId: */ 3),
    ( 3,  'Winterfell  is home', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Fgameofthrones%2Fimages%2F1%2F1f%2F801_Winterfell_Overview.png%2Frevision%2Flatest%3Fcb%3D20190415031728&f=1&nofb=1',
  'Winterfell is the domicile of familiy Stark, who has been ruling the north for decades. The castle is not only home to the Stark children Rob, Sansa, Arya, Bran and Rickon but also to Theon and Jon.'
        , NULL, NULL, /* category: */ 2, DATE (), DATE (), /* UserUserId: */ 3);
