INSERT INTO post(postId, title, image, text, category, createdAt, updatedAt, UserUserId)
VALUES ( 1, 'Arianne Martell', 'https://awoiaf.westeros.org/images/6/61/Ariannemartell1200_tizianobaracchi_by_thaldir-d8zs5u8.jpg', 'Born in 276 AC, Arianne was the firstborn child of her father, Doran Martell, Prince of Dorne, and his wife, Lady Mellario of Norvos. As her fathers firstborn, she was Dorans heiress, according to Rhoynish customs and Dornish laws. Arianne spent several years of her early life at the Water Gardens. She had two younger brothers, but since Quentyn was sent away as a page to Yronwood at an early age and Trystane was eleven years younger than herself, Arianne was never close to them. Instead, her best companions during childhood were Andrey "Drey" Dalt, Garin (whose mother had been her wet nurse), Sylva Santagar, and her cousin Tyene Sand.
                Tyene in particular was Ariannes best friend, since they were the same age, and thus were as close as sisters. Arianne and Tyene shared everything, including learning how to read, ride, and dance; they even shared a flagon of wine they had stolen at the age of ten, and an early attempted sexual experience with Drey. On occasion, Ariannes older cousin Nymeria Sand would join Arianne and her four companions, and sometimes her cousin Sarella Sand would attempt to join them as well. Once, Arianne crossed the Mander in the Reach, when she and three of her cousins went to visit Tyenes mother.
                Arianne once held her young cousin Princess Rhaenys Targaryen, but she was so young at the time that she no longer remembers. She does remember her great-uncle, Prince Lewyn Martell of the Kingsguard, of whom she has cherished memories, and who used to tickle her until she could not stop laughing. When Roberts Rebellion ended, Arianne was seven years old. At the age of eight, Arianne became afflicted with redspots, and learned that the disease, while harmless for children, could be lethal for adults.
                From a young age, Arianne was half in love with her uncle, Prince Oberyn. At some point, Oberyn brought her, Tyene, Sarella Sand, and Garin to the abandoned holdfast of Shandystone. While Oberyn showed Tyene the best way to milk a snakes venom, and Sarella went exploring, Arianne sat on a rock, dreaming that a tall, hard robber knight, with black eyes and a widows peak, had taken her there to have his way with her. '
            , /* category: */ 5, DATE (), DATE (), /* UserUserId: */ 2)
        , ( 2, 'Jon Snow', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/3a1483fe-dc79-4448-8137-c21bf219a1d4/d8pa14z-bf4e5dc1-ac03-48c0-bd62-5ccab261f04b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzNhMTQ4M2ZlLWRjNzktNDQ0OC04MTM3LWMyMWJmMjE5YTFkNFwvZDhwYTE0ei1iZjRlNWRjMS1hYzAzLTQ4YzAtYmQ2Mi01Y2NhYjI2MWYwNGIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.9XvkdiCH08ai8aUFL_uOpzzQpN8dCBPUOk71JNlzkjQ', 'Jon was born in 283 AC, near the end of Roberts Rebellion, and he was named by Lord Eddard Stark. One tale says Jon was named after Lord Jon Arryn, Eddards second father. The identity of Jons mother is a mystery, and several suggestions have been made by those who know the Starks. Jon is unaware of his mothers identity and Eddard refuses to speak of her. When Eddard returned from the war, he brought the newborn Jon to Winterfell, insisting on raising him with the rest of his family. Jon and his wet nurse had been installed in the castle before the arrival of Eddards new wife, Catelyn Tully, and his young son and heir, Robb Stark, from Riverrun, which Catelyn did not take well.
				Lord Eddard was fiercely protective of Jon and refused to send him away. Jon was raised at Winterfell with his half-siblings, where he was tutored by Maester Luwin, and trained at arms by the master-at-arms, Ser Rodrik Cassel. Jon has trained at swordplay since he was old enough to walk, together with Robb, whom he came to view as his "best friend, rival and constant companion," and later also with Theon Greyjoy, after the latter came to Winterfell following the conclusion of Greyjoss Rebellion. Jon learned how to swim in the great moat at Winterfell; he is considered a strong swimmer.
				Jon grew close to his true-born siblings, especially Robb and Arya. Because they look alike, Arya came to believe that she was bastard-born as well, but Jon reassured his half-sister this was not the case. As a young child Jon and Robb built a great mountain of snow on top of a gate, hoping to push it on someone passing by. They were discovered by Mance Rayder, a ranger from the Nights Watch who had accompanied Lord Commander Qorgyle to Winterfell. The ranger promised not to tell anyone, and Jon and Robb succeeded in their ploy, being chased around the yard by Fat Tom, their victim. Jon and Robb would often play a game of sword-play, in which they would pretend to be great heroes (including Florian the Fool, Prince Aemon the Dragonknight, King Daeron I Targaryen, and Ser Ryam Redwyne). Once, when Jon called out that he was "Lord of Winterfell," Robb informed him that it was impossible due to his bastardy, which would become a sore memory for Jon. Another time, Jon covered himself in flour and hid in one of the empty tombs in the crypt of Winterfell, and jumped out to scare Sansa, Arya, and Bran, who had been brought to the crypts by Robb.
				Since he was young, Jons hero was King Daeron, the Young Dragon, who had conquered Dorne at the age of fourteen. Lord Eddard had dreamed about raising new lords and settling them in the abandoned holdfasts in the New Gift, and Jon believes that, had winter come and gone more quickly, he might have been chosen to hold one of the settlements in his fathers name.'
            , /* category: */ 3, DATE (), DATE (), /* UserUserId: */ 3)
        , ( 3,  'Winterfell  is home', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Fgameofthrones%2Fimages%2F1%2F1f%2F801_Winterfell_Overview.png%2Frevision%2Flatest%3Fcb%3D20190415031728&f=1&nofb=1',
                'Winterfell is the domicile of familiy Stark, who has been ruling the north for decades. The castle is not only home to the Stark children Rob, Sansa, Arya, Bran and Rickon but also to Theon and Jon.'
                , /* category: */ 2, DATE (), DATE (), /* UserUserId: */ 4)
        , ( 4,  'Dornishmen', 'https://awoiaf.westeros.org/images/8/80/Diego_Gisbert_Llorens_Desert_RaiderII.png',
                'In Dorne, the descent from the Rhoynar is strongest. The Rhoynar were a slender people with smooth olive skin, black hair and dark eyes. Their impact on the Dornish gene pool is strongest along the coast, and grows faint farther inland. Dornishmen with more Andal and First Men blood are larger and fairer than those with more Rhoynish blood.
                According to King Daeron I Targaryens observations during his wars in Dorne, there are three groups of Dornishmen:
                Salty Dornishmen live along the coasts, mainly along the Broken Arm region, where the Red Mountains stretch out into the Sea of Dorne. These Dornishmen are lithe and dark, with smooth olive skin and long black hair, having been most strongly influenced by the Rhoynar. The Martells of Sunspear would be considered salty Dornishmen.
                Sandy Dornishmen live in the deserts and the long river valleys. With faces burned brown by the hot Dornish sun, they are even darker than the salty Dornishmen. These may include the Ullers and Qorgyles, Houses which were founded by adventurers who braved the deserts.
                Stony Dornishmen live in the passes and heights of the Red Mountains. They have the most Andal and First Men blood. Some stony Dornishmen might follow Andal rather than Rhoynar laws of inheritance. They are fair of skin, freckle or burn in the sun, and have brown or blond hair. These include the Yronwoods with their blond hair and blue eyes, the yellow-haired Fowlers, and the pale blond or dark-haired Daynes.
                Additionally, a fourth, smaller group exists. The orphans of the Greenblood are pure Rhoynar who ply the Greenblood in poleboats. Despite attempts by the Red Princes to extirpate it by outlawing it, they are said to still speak the Rhoynish language discretely. '
                , /* category: */ 5, DATE (), DATE (), /* UserUserId: */ 2)
        , ( 5,  'Weirwood', 'https://3.bp.blogspot.com/-JEvnJTnsYLM/Vvfdbp-EKvI/AAAAAAAAQtc/_vCzWnYAwaYfh2hpcjDET3ohhlHO0YAHw/s1600/Tree_above_the_cave.png',
                'Weirwoods once grew throughout Westeros, although they never took to the thinner soil of the Iron Islands. The children of the forest are said to have carved faces in weirwoods during the Dawn Age, before the coming of the First Men from across the narrow sea. There are still weirwood circles from the children in the high places of Sea Dragon Point.
                The First Men arrived in Westeros by crossing the Arm of Dorne, and began to farm the land and build ringforts and villages, cutting down forest to do so, including the carved weirwoods. This caused the children of the forest to attack them, leading to war. The First Men feared that the childrens greenseers could look through the eyes carved into the trees, and so continued to cut down many weirwood trees and groves with their bronze axes. During the conflict, the First Men made wooden and stone forts, in one case going so far as to build a timber castle entirely from weirwood, called the Bower. Eventually, the two sides fought one another to a standstill, and agreed a Pact at the Isle of Faces, in which the children would leave the land to the First Men, except for the deep forests, while the First Men would no longer cut down the weirwoods. In commemoration of this, all the weirwoods on the Isle were carved with faces so that the gods could witness the Pact, and the green men were formed to protect the Isle and tend to its weirwoods. After the First Men took up the faith of the old gods they created godswoods within their castle walls and villages where a single weirwood, known as a heart tree, was planted so the gods could be worshiped.
                With the invasion of Westeros by Andals came the Faith of the Seven, which viewed the old gods as little more than demons. Some First Men allied with children of the forest, such as the Weirwood Alliance in the Stormlands, and the defenders of the sacred grove of High Heart against Erreg the Kinslayer, who left only the stumps of the thirty-one ancient weirwood trees that had crowned this holy site. Despite this, the Andals eventually conquered most of Westeros except the North, cutting down or burning the weirwoods as they went, and hacking out their carved faces. Once the fighting died down though, the Andal kings sought to consolidate their victories and prevent further bloodshed on the basis of religion, and so kept the weirwoods in their castles godswoods.
                In most of Westeros, the wild weirwoods had been cut or burned down by around 700 BC, except for on the Isle of Faces where the children and the First Men agreed to the peace. As the Andals never conquered the North, the worship of the old gods remains strong there. Weirwoods still grow in the forests of the North, and are prevalent beyond the Wall. '
                , /* category: */ 6, DATE (), DATE (), /* UserUserId: */ 4)
        , ( 6,  'Wildling raids', 'http://www.nationalturk.com/en/wp-content/uploads/2013/02/Game-of-Thrones-Season-3-A-Wildlings.jpg',
                'Raiding south of the Wall is a large part of free folk culture. Raiders start at a young age, as little as twelve years. Raiders either climb the Wall or use little boats to cross the Bay of Seals around it. Climbing the height of the Wall is an exercise that can take most of a day and rangers of the Nights Watch often find the broken bodies of those who have fallen.
                To climb the Wall, the free folk use the aid of huge ladders of woven hemp, boots of supple doeskin spiked with iron, bronze, or jagged bone, small stone-headed hammers, stakes of iron and bone and horn, and antlers with sharpened tines bound to wooden hafts with strips of hide serving as ice axes.
                Over the decades, with the weakening of the Nights Watch, the free folk have found it much easier to either climb the Wall or paddle small boats through the Bay of Seals, growing bolder they raid as far as the Umber lands, the northern mountain clans, or Bear Island, instead of the usual villages and holdfasts in the Gift.
                Raiders cross the Wall to steal swords and axes, spices, silks, furs, and any valuables they can find. They are known to take women in any season to carry them off beyond the Wall. '
                , /* category: */ 2, DATE (), DATE (), /* UserUserId: */ 3)
        , ( 7,  'The story of the rat cook', 'https://awoiaf.westeros.org/images/e/e2/Rat_cook_legend.jpeg',
                'According to legend, the man who would later be known as the Rat Cook was a simple cook at the Nightfort. He became infamous when he served an Andal king (identified either as King Tywell II of the Rock or King Oswell I of the Vale) a pie that was made of bacon and, unknown to the king, the kings son. The cook killed the prince in revenge for a wrong the king supposedly did to him. The king was unaware of this, however, as he ate and praised the taste and asked for a second piece. The gods were angered — not because the cook had committed murder, nor because he had made the king a cannibal — but because the cook had slain a guest beneath his roof. They cursed the cook and transformed him into a massive rat who was doomed to be unable to eat anything but his own young.
                 According to the story, the Rat Cook is an enormous white rat who still lives in the Nightfort today, and all the other rats that inhabit the Nightfort are his descendants. '
                , /* category: */ 3, DATE (), DATE (), /* UserUserId: */ 2)
        , ( 8,  'Three-eyed crow aka. Brynden Rivers', 'http://pm1.narvii.com/6049/1cc16cf5fdf7760cac8dd680aaf5aae0fd44ba96_hq.jpg',
                'First introduced in A Game of Thrones, the three-eyed crow has been a mysterious figure who opened Brans “third eye” to magic, and began him on a path that has led him from Winterfell to the lands beyond the Wall. When we are finally introduced to him, the first and most surprising thing we learn about him is the fact that he is not a child of the forest. Instead, this “pale lord in ebony finery” is a man, ancient and wizened, more a corpse than a live. Bound to a great weirwood, its roots having worked its way into and even through his body, he has waited for many years for Bran—or someone like Bran—to come, to save the world of men from the coming threat.
                For those whove not read the Dunk & Egg stories, the answer as to who this may be may be mystifying. He reveals that he was once a brother of the Watch, that he had a brother he loved and one he despised, and—most importantly—that his name was Brynden, and that Brans great-uncle Brynden Tully may well have been named for him. Putting this all together, theres a hint in A Feast for Crows as to who this is—a companion to Maester Aemon, when he first came to Wall, recently freed from the dungeons by King Aegon V the Unlikely to be able to take the black, and eventually rising to become Lord Commander of the Nights Watch:
                Brynden Rivers, known as Bloodraven, one of the Great Bastards of King Aegon IV the Unworthy. Born an albino and with a large red birthmark on his cheek that was immediately compared to the raven of his mothers house of Blackwood, he grew to become one of the most feared figures in the Seven Kingdoms, helping to bring down the first Blackfyre Rebellion (and allegedly personally killing his brother, Daemon Blackfyre, as well as his sons), supposedly practicing sorcery, and becoming a feared master of spies who became Hand of the King and was said to command “a thousand eyes and one” (referring to his having only a single eye, having lost the other on the Redgrass Field to his half-brother Bittersteel. Many of the details of this splendid figure—Martins nod, in some ways, to Elric of Melnibone—have appeared in the “Dunk and Egg” novels, set almost a hundred years prior to the novels when Brynden was approaching the height of his power and influence, but Martin also provided some key details in a letter to Amok.
                The story of how he came to leave his post as Lord Commander and find his way to the secret cavern of the children of the forest is one that hasnt yet been told.'
                , /* category: */ 6, DATE (), DATE (), /* UserUserId: */ 4)
        , ( 9,  'I wish Rickon was older', 'https://i.pinimg.com/736x/ef/34/f3/ef34f3744e17d3cf532f7752eba2c8bd--house-stark-game-of.jpg',
                'Specifically Rickon, because all of the stark men we observe all have similar temperaments: generally calm. But Rickon not, hes prone to outbursts.'
                , /* category: */ 2, DATE (), DATE (), /* UserUserId: */ 5)
;
